### ISSUE TITLE
Cache client support multiple key

### ISSUE THREAD

**Issue by shibd** [openmessaging/openchaos#25]
## 背景

在用cache 模型测试时，put请求希望可以支持多个key，这样可以测试存储的多个主节点处理数据的情况。

**Comment by vongosling** [comment]
Would you like to detail your description,  how to use multi-key when testing multi-nodes?

**Comment by shibd** [comment]
Yes, Take dledger for example, Multiple keys will be distributed on different nodes, Every node is a master, This test is more comprehensive.

dledger doesn't seem to support it multi-raft module.
