### ISSUE TITLE
Is this project inspired by jepsen?

### ISSUE THREAD

**Issue by Tsunaou** [openmessaging/openchaos#54]
Our research group are doing works about "translating" jepsen from clojure to other languages.
(See [jepsen-in-java](https://github.com/hengxin/jepsen-in-java), [jepsen-in-python](https://github.com/hengxin/jepsen-in-python), and [jepsen-in-cpp](https://github.com/hengxin/jepsen-in-cpp).)
It's delightful to find someone doing something similar.

**Comment by vongosling** [comment]
I should say yes, Consensus evaluation is the main goal for Jepsen. OpenChaos is aim for resilience architecture, especially for modern data architecture.
